# More GitHub Actions for Azure: https://github.com/Azure/actions

name: zip and commit extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip-and-commit:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create zip file
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension.zip . -i extension

    - name: Commit zip file
      uses: EndBug/add-and-commit@v9
      with:
        add: 'extension.zip'
        default_author: github_actions